requirements.txt

mkdocs is looking for minify and it currently isn't installed causing my builds to fail (unless I am fundamentally doing something wrong?) 
Added to requirements for installer

Adding in dependency -minify

---

requirements.txt

This PR fixes the `docker build` errors by using version pinning for mkdocs and plugins.

Pin mkdoc versions

---

docs/tutorial/image-building-best-practices/index.md

The description in the `Layer Caching` section of the `Image Building Best Practices` page of the tutorial mentioned the following:
> Now that you've seen the layering in action, there's an important lesson to learn to help **increase** build times for your container images.
but the suggestions mentioned in the section were to reduce the build time of the container images. Seems like the intent was wrongly mentioned in the above description. This is what was corrected to the following in this PR
> Now that you've seen the layering in action, there's an important lesson to learn to help **decrease** build times for your container images.

correct intent in 'Layer Caching' description

---

docs/tutorial/multi-container-apps/index.md
docs/tutorial/using-bind-mounts/index.md
docs/tutorial/using-docker-compose/index.md

Explain the `-v` option in "Using Bind mounts" chapter.
Fixes #30 
This PR also adds an explanation to change backslashes `\` to backticks `` ` `` for Windows PowerShell users.
@mikesir87 WDYT? (I finally learn how to write a backtick in code blocks 😆)

Explain `-v` option, explain how to write long PowerShell commands

---

docs/tutorial/using-bind-mounts/index.md

The recently added description for the -v flag contained a typo in the word mount.

Fix typo in -v description

---

app/src/static/js/app.js

If the user clicks on the `<i>` element, the `onClick` event is propagated to the `<button>` which results in duplicate PUT request to the server.

Avoid sending duplicate PUT requests when toggling completion

---

docs/tutorial/image-building-best-practices/index.md

The Dockerfile listed above specifically uses package.json, but the
output listed for the build lists package*, which is inconsistent. The
React example later in the doc uses package*, which would be consistent
with the output, but this should fix the mismatch for the beginner going
through the tutorial for the first time.
Additionally, the sentence "Build the Docker image now using 'docker
build' again" might be confusing to a beginner. I specifically tested
running this exact command and it gives an error message. Specifically
using the exact command needed to build this target shouldn't take up
too much space.

Match output to input and clarify build command

---

app/src/persistence/mysql.js

proposition to close #48
By removing the timeout, the todo application wait for the mysql container to be fully initialized and then create the connection.
It fixes the issue for me. Let me know if it would be a good solution. Or an other approach, such as implementing a fallback on the timeout to prevent the application from failing would be a better solution.

Removes timeout on mysql connection

---

README.md

The README suggests to run the docker/getting-started container with combined `-dp 80:80` parameters.
The tutorial itself shows seperate flags `-d` and `-p 80:80` and explains it.  We should adjust the README and use the beginners friendly command.
Also did some markdown cleanup in VSCode.

Use single shorthand flags, better for beginners

---

docs/tutorial/persisting-our-data/index.md

The original language implies that SQLite is not an "actual" database engine, which is of course not the case! SQLite is a very capable and ubiquitous database engine. It's not appropriate for many applications, though, so perhaps the document here can simply read "different" rather than "actual". I recognize this is a bit particular, but hey-- that's how I perceived the language on my first read, and I don't even particularly like (or use) SQLite anyways! I do respect the technology, though, and thought it'd be kind to change the language so as to remove all possibility of misinterpretation.

Fix slightly snide comment about SQLite

---

docs/tutorial/multi-container-apps/index.md
docs/tutorial/using-bind-mounts/index.md
docs/tutorial/using-docker-compose/index.md

Show all multiline commands both for `bash` (Linux, Mac, WSL 2) and PowerShell. PowerShell uses a different line continuation character. We explained what to change, but it's easier for the users to have a copy-pastable command that works in PowerShell.
Fixes #64 
Also switch from `-v ${PWD}:/app` to `-v "$(pwd):/app"` to support more Linux distributions. The quotes are needed in PowerShell, and may be needed if a Linux user has the sample source code in a path that contains spaces.
Fixes #14

Show multiline PowerShell commands

---

Dockerfile
build.sh

For non-amd64 platforms we need python, make and g++ to compile sqlite3 node module.
Removing arm 32bit from build.sh script as we don't need it on these platforms to save build time.
This change is required to have a smooth onboarding experience on Apple Silicon machines.

Build amd64 and arm64 image

---

docs/tutorial/our-application/index.md

Fix the `Dockerfile` in the tutorial just like we did in #104 to make the `docker build -t getting-started .` command work on Apple Silicon or other arm64 machines.

Add build tools to fix arm64 build issue

---

docs/tutorial/our-application/index.md

This line did not appear to be necessary for the tutorial. Testing with it removed appeared to have no effect. Additionally, this line does not appear later in the tutorial when referring back to this step (see /docs/tutorial/image-building-best-practices/index.md).

Removed 'RUN apk add --no-cache python g++ make'

---

docs/tutorial/persisting-our-data/index.md

Hi maintainers docker team,
This is the first time I have creating PR to this repository, I would like to add some documentation that was missing container-id, can you check?
The idea is to make people straightforward for their learning purposes by this documentation.
Thank you

docs: Fix missing container id

---

docs/tutorial/using-docker-compose/index.md

- Reference URLs to short/long syntax and volumes config options in Docker Compose section are leading to Compose file reference/Compose Specification in the docs, instead of to the specific instructions for Version 3 or 2. This can be a bit confusing to beginners like me, wondering if I was missing something to get the right link.

Update reference links in docker compose section.

---

Dockerfile
docs/tutorial/our-application/index.md

The tutorial regularly fails for users because of the tons of dependencies that has to be pulled and installed during the test phase of the Dockerfile. Then it failed for Apple M1 users due to missing build tools to compile some native Node.js packages. All in all we put more dependencies into this and slowed down the whole experience of the "Getting Started Guide" in Docker Desktop.
I now looked closer and realised that the test step isn't required, so I just removed the additional dependencies and the whole test step. So the tutorial is much faster again and less likely to fail.
For the later tutorial when an user walks through all the steps, the Dockerfile shown to use actually has the build dependencies, so it will work for all users, both working with Intel/AMD machines as well as …

Faster getting started guide, fix for Apple silicon

---

app/package.json
app/src/index.js

Express 4.16+ uses body-parser by default so it is not necessary to add body-parser as a dependency unless you absolutely require it. This PR removes the use of the package from the code.
[Refer to this article for more details.](https://medium.com/@mmajdanski/express-body-parser-and-why-may-not-need-it-335803cd048c)

Removed body-parser as a dependency.

---

docs/tutorial/using-bind-mounts/index.md

The command for bind mount doesn't run in Ubuntu if the user is not in the source code folder. At least, for me didn't work. So I specified that to prevent errors and bugs.

Update index.md from using bind mount

---

docs/tutorial/sharing-our-app/index.md

I was going through the docs of docker and found that the play with docker points to the wrong link it goes to the homepage instead of the app.

Point To The Correct Link For Play With Docker

---

app/spec/persistence/sqlite.spec.js

- Path `/etc/todos/todo.db` is hardcoded [here](https://github.com/docker/getting-started/blob/13386236e44b3b599e68faf3ee187894b42969b7/app/spec/persistence/sqlite.spec.js#L11). This fails tests if I don't have edit access to `/etc` on my system
- changed it to take this path from the env variable `SQLITE_DB_LOCATION` and take `'/etc/todos/todo.db'` as a fallback just like [here](https://github.com/docker/getting-started/blob/13386236e44b3b599e68faf3ee187894b42969b7/app/src/persistence/sqlite.js#L3)

fix: path to db file in test

---

docs/tutorial/our-application/index.md

I could not successfully run `docker build -t getting-started .` command in 'Our Application' tutorial with original docker file. It was because the `yarn install --production` command depended on python2.
After I added python2 instead of python3 into the docker file, I could successfully build the docker image.

fix on 'Our Application' tutorial for Apple silicon

---

docs/tutorial/using-bind-mounts/index.md

With many thanks to [@samjewell](https://github.com/docker/getting-started/issues/124#issuecomment-782028688).
Also, at this point in the tutorial, it's not clear that this command isn't using the `Dockerfile` added in the 2nd step.  I'm not sure how to communicate that, so I've left it out.  I found [this comment](https://github.com/docker/getting-started/issues/36#issuecomment-753847145) and could see that my `Dockerfile` already had the sqlite3 deps, so was pulling my hair out resetting & uninstalling Docker trying to get it to work. :/
Hopefully closes #124

Update dev mode command to install sqlite3 deps

---

docs/tutorial/index.md

Fixed dead links that resulted in 404 errors.
- https://docs.docker.com/docker-for-mac/dashboard/
- https://docs.docker.com/docker-for-windows/dashboard/
Updated to a single link to https://docs.docker.com/desktop/
Fixes https://github.com/docker/docker.github.io/issues/15387

Fix dead links

---

app/src/persistence/mysql.js

I was helping troubleshoot an issue with someone, who ended up having a typo in their compose file where the MySQL service was using the name "msyql", which obviously causes DNS to fail. But, since the db init doesn't time out, it just looks hung. This fixes that.

Update MySQL handler to add timeout for DNS query failures

---

docs/tutorial/using-bind-mounts/index.md

This change simply adds clarification that removal of the `getting-started` containers should be only for your own containers and leave the tutorial itself running.
Resolves #28

Clarify removal of containers shouldn't remove tutorial

---

.github/workflows/build.yml
Dockerfile

Since the initial mkdocs build and app ZIP creation is platform-independent, I added the `--platform=$BUILDPLATFORM` to reuse the outputs from those stages. Only the final nginx stage uses the `--platform=$TARGETPLATFORM`.

Add platform flags to Dockerfile to speed up builds

---

docs/tutorial/our-application/index.md

fix(docs/tutorial/our-application): update index.md
