- Dockerfile
> Remove unused ARG from Dockerfile

- docs/tutorial/using-docker-compose/index.md
> Typo fix in docker compose tutorial

- docs/tutorial/multi-container-apps/index.md
- docs/tutorial/using-bind-mounts/index.md
- docs/tutorial/using-docker-compose/index.md
Signed-off-by: Michael Irwin <mikesir87@gmail.com>
Resolves #7
> Add curly brackets around $PWD usage to fix powershell issues

- app/src/static/index.html
Signed-off-by: Michael Irwin <mikesir87@gmail.com>
Work-around for #9 while trying to figure out what's going on
> Removed SRI hashes from index.html

- docs/tutorial/using-docker-compose/index.md
I think the changes speak for themselves, they're some minor fixes 
Also I'd like to say this is a very cool thing, just the right bite-sized amounts of information that gives me enough info to use this in my own projects :slightly_smiling_face:.
> Minor text tweaks in docker compose chapter

- docs/tutorial/image-building-best-practices/index.md
Fixes #46
Kindly requesting feedback 🙂
> Add .dockerignore for node_modules & explanation

- Jenkinsfile
Automate the image build and push to Docker Hub after changes in master branch.
Fixes #55
> Add Jenkinsfile to push image

- docs/tutorial/image-building-best-practices/index.md
- docs/tutorial/our-application/index.md
CMD runs relative to the WORKDIR.
> Dockerfile CMD path fix

- Jenkinsfile
This fixes the docker build command in the Jenkins pipeline.
> Fix build command

- docs/tutorial/multi-container-apps/index.md
> Update docs w/ missing "to"

- .github/workflows/build.yml
This makes sure the project builds correctly on pushes to branches and pull requests.
See what it does here: https://github.com/mat007/getting-started/runs/1035639620
> Add github action to build

- docs/tutorial/using-bind-mounts/index.md
> Edit docs/tutorial/using-bind-mounts/index.md

- docs/tutorial/multi-container-apps/index.md
The suggested bullet sign used "- " does not display.
Am using google chrome browser Version 88.0.4324.190 (Official Build) (64-bit)
> Period omission at the end of line 7,8 and 10. 

- docs/tutorial/using-bind-mounts/index.md
Minor gotcha but might help since save step is not explicit and the context is around auto-refresh feature.
> Add reminder to save file for the app refresh change

- app/src/static/js/app.js
This reverts commit 7bb2ef8c6d9cbd418a8f6241bc164dc3555ff5af of PR #192.
It's part of the tutorial to make this change, so we should keep the code in the repo in its original state.
> Revert "Update app.js"

- app/src/persistence/mysql.js
Solve the error when typing emoji.
> support emoji

- docs/tutorial/multi-container-apps/index.md
This fixes the display of some code blocks by correcting the code fence indent level
> Fix some code fences and whitespace on "multi-container apps"

- docs/tutorial/using-docker-compose/index.md
> doc(using-docker-compose): update docker file reference

- docs/tutorial/multi-container-apps/index.md
> Add instruction to exit out of the netshoot container when done

- docs/tutorial/using-docker-compose/index.md
Add a little bit of text to clarify where the Compose file should be located during creation.
Resolves #102
> Clarify where the compose file should be located
